export const API = {
  admin: {
    login: "/api/auth/login",
    stats: "/api/admin/stats",
  },
  user: {
    search: "/api/user/search",
    get: (userId: string) => `/api/user/${userId}`,
    updateRole: (userId: string) => `/api/user/${userId}/role`,
    delete: (userId: string) => `/api/user/${userId}`,
    notifications: "/api/user/me/notifications",
    report: "/api/user/report",
    all: "/api/user/all",
  },
  anime: {
    getAll: "/api/anime",
    get: (id: string) => `/api/anime/${id}`,
    create: "/api/anime",
    update: (id: string) => `/api/anime/${id}`,
    delete: (id: string) => `/api/anime/${id}`,
    search: "/api/anime/search",
    lookup: "/api/anime/lookup",
    featured: (animeId: string) => `/api/anime/${animeId}/featured`,
    unfeatured: (animeId: string) => `/api/anime/${animeId}/unfeatured`,
  },
  season: {
    getByAnime: (animeId: string) => `/api/season/anime/${animeId}`,
    get: (id: string) => `/api/season/${id}`,
    create: (animeId: string) => `/api/season/anime/${animeId}`,
    update: (seasonId: string, animeId: string) =>
      `/api/season/${seasonId}/anime/${animeId}`,
    delete: (seasonId: string, animeId: string) =>
      `/api/season/${seasonId}/anime/${animeId}`,
  },
  episode: {
    getBySeason: (animeId: string, seasonId: string) =>
      `/api/episode/anime/${animeId}/season/${seasonId}`,
    get: (id: string) => `/api/episode/${id}`,
    create: (animeId: string, seasonId: string) =>
      `/api/episode/anime/${animeId}/season/${seasonId}`,
    update: (id: string) => `/api/episode/${id}`,
    delete: (id: string) => `/api/episode/${id}`,
  },
  genre: {
    getAll: "/api/genre",
    get: (id: string) => `/api/genre/${id}`,
    create: "/api/genre",
    update: (id: string) => `/api/genre/${id}`,
    delete: (id: string) => `/api/genre/${id}`,
  },
  character: {
    getAll: "/api/character",
    get: (id: string) => `/api/character/${id}`,
    create: "/api/character",
    update: (id: string) => `/api/character/${id}`,
    delete: (id: string) => `/api/character/${id}`,
    search: "/api/character/search",
  },
  comment: {
    getAll: "/api/comment",
    get: (id: string) => `/api/comment/${id}`,
    create: "/api/comment",
    update: (id: string) => `/api/comment/${id}`,
    delete: (id: string) => `/api/comment/${id}`,
    search: "/api/comment/search",
    approve: (id: string) => `/api/comment/${id}/approve`,
    reject: (id: string) => `/api/comment/${id}/reject`,
  },
  forum: {
    getAll: "/api/forums/admin",
    create: "/api/forums/admin",
    update: (id: string) => `/api/forums/admin/${id}`,
    delete: (id: string) => `/api/forums/admin/${id}`,
    createCategory: "/api/forums/admin/categories",
    updateCategory: (id: string) => `/api/forums/admin/categories/${id}`,
    deleteCategory: (id: string) => `/api/forums/admin/categories/${id}`,
    getAllTopics: "/api/forums/admin/topics",
    getTopicsByForum: (forumId: string) =>
      `/api/forums/admin/${forumId}/topics`,
    createTopic: "/api/forums/admin/topics",
    getTopic: (id: string) => `/api/forums/admin/topics/${id}`,
    updateTopic: (id: string) => `/api/forums/admin/topics/${id}`,
    deleteTopic: (id: string) => `/api/forums/admin/topics/${id}`,
    pinTopic: (id: string) => `/api/forums/admin/topics/${id}/pin`,
    lockTopic: (id: string) => `/api/forums/admin/topics/${id}/lock`,
    stickyTopic: (id: string) => `/api/forums/admin/topics/${id}/sticky`,
    deletePost: (id: string) => `/api/forums/admin/posts/${id}`,
  },
};
